# Generated by Django 3.2.3 on 2021-06-18 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.IntegerField(blank=True, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('other_expanses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='vendor_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_person', models.TextField(blank=True, null=True)),
                ('contact_number', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst_no', models.TextField(blank=True, null=True)),
                ('name_of_bank', models.TextField(blank=True, null=True)),
                ('acc_no', models.TextField(blank=True, null=True)),
                ('ifsc_code', models.TextField(blank=True, null=True)),
                ('branch', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='work_order',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.order')),
                ('party_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vendor_details')),
            ],
            bases=('main.order',),
        ),
        migrations.CreateModel(
            name='indent',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.order')),
                ('material_shape', models.TextField(blank=True, null=True)),
                ('material_type', models.TextField(blank=True, null=True)),
                ('size', models.IntegerField()),
                ('thickness', models.IntegerField()),
                ('width', models.IntegerField()),
                ('internal_diameter', models.IntegerField()),
                ('work_order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.work_order')),
            ],
            bases=('main.order',),
        ),
    ]
