# Generated by Django 3.1 on 2021-08-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210830_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard_weight',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
