# Generated by Django 3.1 on 2021-08-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_standard_weight_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='size',
        ),
        migrations.AlterModelOptions(
            name='standard_weight',
            options={'verbose_name_plural': 'Standard Weight'},
        ),
        migrations.AlterModelOptions(
            name='vendor_details',
            options={'verbose_name_plural': 'Vendor Details'},
        ),
        migrations.RenameField(
            model_name='indent',
            old_name='party_name',
            new_name='vendor_name',
        ),
        migrations.AddField(
            model_name='vendor_details',
            name='vendor_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work_order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='standard_weight',
            constraint=models.UniqueConstraint(fields=('size', 'material_shape'), name='Shape and size cannot be same.'),
        ),
        migrations.AddConstraint(
            model_name='vendor_details',
            constraint=models.UniqueConstraint(fields=('vendor_name', 'contact_person'), name='Vendor name and contact person cannot be same.'),
        ),
    ]
