# Generated by Django 3.2.3 on 2021-08-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210830_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='indent',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='recived',
            field=models.BooleanField(default=False),
        ),
    ]
