# Generated by Django 3.2.3 on 2021-08-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210830_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
