# Generated by Django 3.2.3 on 2021-08-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
