# Generated by Django 3.2.3 on 2021-09-01 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_order_po_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='po_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='po_number',
        ),
        migrations.CreateModel(
            name='purchase_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=200, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('vendor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vendor_details')),
            ],
        ),
    ]
