# Generated by Django 3.2.3 on 2021-09-01 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210901_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indent',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='indent',
            name='PO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.purchase_order'),
            preserve_default=False,
        ),
    ]
