# Generated by Django 3.2.3 on 2021-09-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210901_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order',
            old_name='vendor_name',
            new_name='vendor_id',
        ),
    ]
