# Generated by Django 3.2.3 on 2021-09-01 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_vendor_name_purchase_order_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order',
            name='PO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.purchase_order'),
            preserve_default=False,
        ),
    ]
