# Generated by Django 3.2.3 on 2021-09-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_work_order_party_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
