# Generated by Django 3.2.3 on 2021-09-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_purchase_order_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order',
            old_name='is_completed',
            new_name='is_complete',
        ),
    ]
