# Generated by Django 3.2.3 on 2021-09-02 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210902_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_order',
            old_name='is_active',
            new_name='is_complete',
        ),
        migrations.AddField(
            model_name='work_order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work_order',
            name='incoming_po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work_order',
            name='incoming_po_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work_order',
            name='item_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.item_description'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='vendor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vendor_details'),
        ),
        migrations.AddField(
            model_name='work_order',
            name='wo_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
