# Generated by Django 3.2.3 on 2021-09-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210903_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='other_expanses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
