# Generated by Django 3.2.3 on 2021-09-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_order_other_expanses'),
    ]

    operations = [
        migrations.AddField(
            model_name='indent',
            name='WO',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='main.work_order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indent',
            name='PO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.purchase_order'),
        ),
    ]
