# Generated by Django 3.2.3 on 2021-09-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_purchase_order_work_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order',
            name='wo_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
