# Generated by Django 3.2.3 on 2021-09-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_vendor_details_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='grn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('indent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.indent')),
            ],
        ),
    ]
