# Generated by Django 3.2.3 on 2021-09-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210907_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='indent',
            name='recived_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
