# Generated by Django 3.2.3 on 2021-09-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210911_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='indent',
            name='recived_quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddConstraint(
            model_name='grn',
            constraint=models.UniqueConstraint(fields=('invoice_no', 'indent_id'), name='Same invoice cannot be in the same indent.'),
        ),
    ]
