# Generated by Django 3.2.3 on 2021-09-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_indent_material_shape'),
        ('main', '0030_auto_20210915_2305'),
    ]

    operations = [
    ]
