# Generated by Django 3.2.3 on 2021-09-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_grn_vendor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grn',
            options={'verbose_name_plural': 'GRN'},
        ),
        migrations.AlterField(
            model_name='grn',
            name='indent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.indent'),
        ),
    ]
