# Generated by Django 3.2.3 on 2021-10-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210916_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
