# Generated by Django 3.2.3 on 2021-10-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_purchase_order_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order',
            name='locked',
        ),
        migrations.AddField(
            model_name='indent',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
