# Generated by Django 3.2.3 on 2021-10-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20211001_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('items', models.ManyToManyField(to='main.item_description')),
            ],
        ),
    ]
