# Generated by Django 3.2.3 on 2021-10-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_assembly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembly',
            options={'verbose_name_plural': 'Assembly'},
        ),
    ]
