# Generated by Django 3.2.3 on 2021-11-19 14:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_assembly_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='item_json',
            field=main.models.JSONField(default={}),
            preserve_default=False,
        ),
        
    ]
