# Generated by Django 3.2.3 on 2021-11-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20211119_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_description',
            name='estimated_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
