# Generated by Django 3.2.3 on 2021-11-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_item_description_estimated_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='estimate_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
