# Generated by Django 3.2.3 on 2021-11-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_assembly_estimate_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_description',
            name='shape',
            field=models.CharField(choices=[('Round', 'Round'), ('Plate', 'Plate'), ('SQ Bar', 'SQ Bar'), ('Pipe', 'Pipe'), ('BF', 'BF'), ('Labour', 'Labour'), ('ISMC', 'ISMC'), ('ISMB', 'ISMB'), ('ISA', 'ISA'), ('Bolt', 'Bolt'), ('Nut', 'Nut')], default='Round', max_length=20),
            preserve_default=False,
        ),
    ]
