# Generated by Django 3.2.3 on 2021-12-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_item_description_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='estimate',
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
