# Generated by Django 3.2.3 on 2021-12-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20211209_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='item_state',
            new_name='assembly_json',
        ),
    ]
