# Generated by Django 3.2.3 on 2021-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_rename_item_state_plan_assembly_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='assemblies',
            field=models.ManyToManyField(blank=True, null=True, to='main.assembly'),
        ),
    ]
