# Generated by Django 3.2.3 on 2022-01-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_item_description_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='assemblies',
            field=models.ManyToManyField(to='main.assembly'),
        ),
    ]
